# Generated by Django 5.2 on 2025-05-12 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_userranking"),
    ]

    operations = [
        migrations.AddField(
            model_name="userranking",
            name="best_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mainapp.job",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Finishing", "Finishing"),
                    ("Favored", "Favored"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
