# Generated by Django 5.2 on 2025-05-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_userranking_best_job_alter_job_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="rank_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
